/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theia;

import java.io.IOException;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

/**
 *
 * @author arun
 */
public class InstanceUrlCapture extends javax.swing.JFrame {

    /**
     * Creates new form EnginSelectorWindow
     */
    public InstanceUrlCapture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instanceUrlField = new javax.swing.JTextField();
        instanceSelectButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        defaultInstanceText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        instanceUrlField.setText("Enter the searx instance url here");
        instanceUrlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instanceUrlFieldActionPerformed(evt);
            }
        });

        instanceSelectButton.setText("Select");
        instanceSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instanceSelectButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Theia v1.0");

        defaultInstanceText.setText("Leave Field Empty for Default Instance");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(instanceUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(instanceSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(defaultInstanceText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instanceUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instanceSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(defaultInstanceText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void instanceSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instanceSelectButtonActionPerformed

        String instanceUrl = instanceUrlField.getText();
        if (instanceUrl.length() == 0 || instanceUrl.equals("Enter the searx instance url here") == true) {
            instanceUrl = "https://search.disroot.org";
            System.out.println("The searx instance being used is " + instanceUrl);
            this.setVisible(false);
            this.dispose();
            new SearchWindow(instanceUrl).setVisible(true);
        } else {

            try {
                Document document = Jsoup.connect(instanceUrl + "/search?q=apple").get();
                Elements text = document.select("div[class=external-link]");
                String[] links = new String[text.size()];
                for (int i = 0; i < text.size(); i++) {
                    links[i] = text.get(i).text();
                }
                if (links.length == 0 || links == null) {
                    defaultInstanceText.setText("Wrong or Invalid Instance Url");
                } else {
                    System.out.println("The searx instance being used is " + instanceUrl);
                    this.setVisible(false);
                    this.dispose();
                    new SearchWindow(instanceUrl).setVisible(true);
                }

            } catch (Exception e) {
                defaultInstanceText.setText("Wrong or Invalid Instance Url");
            }
        }

    }//GEN-LAST:event_instanceSelectButtonActionPerformed

    private void instanceUrlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instanceUrlFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instanceUrlFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstanceUrlCapture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstanceUrlCapture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstanceUrlCapture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstanceUrlCapture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstanceUrlCapture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel defaultInstanceText;
    private javax.swing.JButton instanceSelectButton;
    private javax.swing.JTextField instanceUrlField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
