package theia;

import java.util.ArrayList;

/**
 *
 * @author arun
 */
public class SearchWindow extends javax.swing.JFrame {
    
    String instanceUrl;

    /**
     * Creates new form SearchWindow
     * @param instanceUrl
     */
    public SearchWindow(String instanceUrl) {
        this.instanceUrl = instanceUrl;
        initComponents();
        emptytTheList();
    }

    private void emptytTheList() {
        String links[] = {""};
        searchResultList.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() {
                return links.length;
            }

            @Override
            public String getElementAt(int i) {
                return links[i];
            }
        });
    }
    
    private void printErrorToList(String error_message) {
        String errors[] = {error_message};
        searchResultList.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() {
                return errors.length;
            }

            @Override
            public String getElementAt(int i) {
                return errors[i];
            }
        });
    }
    
    private void updateToList(String links[]) {
        searchResultList.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() {
                return links.length;
            }

            @Override
            public String getElementAt(int i) {
                return links[i];
            }
        });
    }
     
        
    private ArrayList<String> checkBoxMonitor()
    { 
        
       ArrayList<String> engines_checked = new ArrayList<String>();
       
       if(google.isSelected()==true)
       {
           engines_checked.add("google");
       }
       if(duckduckgo.isSelected()==true)
       {
           engines_checked.add("duckduckgo");
       }
       if(wikipedia.isSelected()==true)
       {
           engines_checked.add("wikipedia");
       }
       if(youtube.isSelected()==true)
       {
           engines_checked.add("youtube");
       }
       if(reddit.isSelected()==true)
       {
           engines_checked.add("reddit");
       }
       if(bing.isSelected()==true)
       {
           engines_checked.add("bing");
       }
       if(piratebay.isSelected()==true)
       {
           engines_checked.add("piratebay");
       }
        if(brave.isSelected()==true)
       {
           engines_checked.add("brave");
       }
       if(libgen.isSelected()==true)
       {
           engines_checked.add("library genesis");
       }
             
       // String engines_list[] = {"gogole","duckduckgo","wikipedia","youtube","reddit","bing","brave","piratebay","libgen"};
        return engines_checked;
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        google = new javax.swing.JCheckBox();
        duckduckgo = new javax.swing.JCheckBox();
        wikipedia = new javax.swing.JCheckBox();
        youtube = new javax.swing.JCheckBox();
        reddit = new javax.swing.JCheckBox();
        bing = new javax.swing.JCheckBox();
        brave = new javax.swing.JCheckBox();
        piratebay = new javax.swing.JCheckBox();
        libgen = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        google.setText("Google");
        google.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                googleActionPerformed(evt);
            }
        });

        duckduckgo.setText("DuckDuckGo");
        duckduckgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duckduckgoActionPerformed(evt);
            }
        });

        wikipedia.setText("Wikipedia");
        wikipedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wikipediaActionPerformed(evt);
            }
        });

        youtube.setText("Youtube");
        youtube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youtubeActionPerformed(evt);
            }
        });

        reddit.setText("Reddit");

        bing.setText("Bing");

        brave.setText("Brave");

        piratebay.setText("Pirate Bay");

        libgen.setText("LibGen");

        searchResultList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(searchResultList);

        jLabel1.setText("Enter the search keywords here : ");

        jLabel2.setText("Select engine(s) :");

        jLabel3.setText("Result(s) :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(google)
                                .addGap(18, 18, 18)
                                .addComponent(duckduckgo)
                                .addGap(18, 18, 18)
                                .addComponent(wikipedia)
                                .addGap(18, 18, 18)
                                .addComponent(youtube)
                                .addGap(18, 18, 18)
                                .addComponent(reddit)
                                .addGap(18, 18, 18)
                                .addComponent(bing)
                                .addGap(18, 18, 18)
                                .addComponent(brave)
                                .addGap(18, 18, 18)
                                .addComponent(piratebay)
                                .addGap(18, 18, 18)
                                .addComponent(libgen))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(google)
                    .addComponent(duckduckgo)
                    .addComponent(wikipedia)
                    .addComponent(youtube)
                    .addComponent(reddit)
                    .addComponent(bing)
                    .addComponent(brave)
                    .addComponent(piratebay)
                    .addComponent(libgen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        String search_keyword = searchField.getText();
        
        if(search_keyword.length()==0)
        {
            printErrorToList("The Search Field is Empty");
        }
        else
        { 
            int len = checkBoxMonitor().size();
            if(len==0)
            {
                printErrorToList("No Engines Selected");
                
            }
            else
            {
                    QueryGenerator generator  = new QueryGenerator(search_keyword,checkBoxMonitor());
                    String query = generator.getQuery();
                    
                    QueryMaker maker = new QueryMaker(instanceUrl,query);
                    String links[] = maker.getExternalLinks();
                    if(links==null||links.length==0)
                    {
                        printErrorToList("No Results Found :(");
                    }
                    else
                    {
                    updateToList(links);
                    }
            }                      
        }
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void googleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_googleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_googleActionPerformed

    private void duckduckgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duckduckgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duckduckgoActionPerformed

    private void wikipediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wikipediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wikipediaActionPerformed

    private void youtubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youtubeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_youtubeActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bing;
    private javax.swing.JCheckBox brave;
    private javax.swing.JCheckBox duckduckgo;
    private javax.swing.JCheckBox google;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox libgen;
    private javax.swing.JCheckBox piratebay;
    private javax.swing.JCheckBox reddit;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JList<String> searchResultList;
    private javax.swing.JCheckBox wikipedia;
    private javax.swing.JCheckBox youtube;
    // End of variables declaration//GEN-END:variables
}
